### ISSUE TITLE
Increase exchange-api starting timeout value

### ISSUE THREAD

**Issue by sirotsinskuy** [open-horizon/devops#18]
It would be good to have the exchange-api starting timeout bigger that 20 seconds (at least 30 sec, maybe up to 1 minute), as it could be the problem for some users. For my case - I was able to fit into that timeout after 3 times of trying and each time I had
`Error: can not reach the exchange at http://127.0.0.1:3090/v1 (tried for 20 seconds): curl: (52) Empty reply from server`

**Comment by joewxboy** [comment]
@bmpotter This is the second or third time I've heard this complaint from someone running the all-in-1 install script.  On some machines and/or in some environments, they really need more time for the process to complete successfully.  Would the solution be to increase the default timeout, allow an override for the timeout and discuss in documentation, or some other approach?

**Comment by bmpotter** [comment]
@joewxboy there already are overrides. See all of the env vars, starting at https://github.com/open-horizon/devops/blob/3b1e3f78f24a7b82023666349b6ebd4e88173611/mgmt-hub/deploy-mgmt-hub.sh#L85 . When there is syntax like:

```
export EXCHANGE_WAIT_ITERATIONS=${EXCHANGE_WAIT_ITERATIONS:-10}
```

that means use the value of `EXCHANGE_WAIT_ITERATIONS` the user has set in their environment, otherwise default to 10.

But i also just submitted a PR to increase the default and made you a reveiwer: https://github.com/open-horizon/devops/pull/19
