### ISSUE TITLE
Error installing socat on OSX in deploy_mgmt_hub.sh

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/devops#36]
I ran the `deploy_mgmt_hub.sh` script for the first time on a MacBook Pro with a recent OSX.  Near the end of the install process, the script checks to see if socat is installed, and attempts to install it if it is not present.  Since the install script is running as root using sudo, this can be problemmatic with some package managers.

In this particular case, it appears to be trying to use MacPorts to install socat.  This fails on my MacBook because MacPorts is not installed.  It recommends `sudo port install socat` which fails because "port" is not on my machine.

I do have `homebrew` installed, so if I drop out of sudo back to a user account and run `brew install socat` and then `sudo -i` to become root again, and then run `./deploy_mgmt_hub.sh` again, it works.

I'm not sure if the solution here is to check for socat at the beginning of the script and tell OSX users to install socat manually if it does not exist, or if there is a better solution.  I just thought you'd want to know that it does not currently work for users in my situation on fresh OSX installs.

**Comment by bmpotter** [comment]
@joewxboy I'm confused by this. First, there is no reference to socat in `deploy-mgmt-hub.sh`. It is the `anax/anax-in-container/horizon-container` that checks for `socat` and starts/stop it when necessary. But i don't see anywhere that `horizon-container` tries to install `socat`, instead of tells the user to install it [here](https://github.com/open-horizon/anax/blob/b604ff0642a53bba2b90c02b0728628793f38d81/anax-in-container/horizon-container#L114) .

**Comment by joewxboy** [comment]
That must have been what I saw, and assumed that it attempted installation.  Closing.
